language: ruby
sudo: false
cache: bundler
script: if [ $TRAVIS_BRANCH == "master" ]; then bundle exec middleman build; fi
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  keep-history: true
  on:
    branch: master
notifications:
  email: false
  slack:
    on_pull_requests: false
    rooms:
      - secure: $SLACK_TOKEN
    on_success: change
    on_failure: always